### ISSUE TITLE
Rename the folder to memorygame

### ISSUE THREAD

**Issue by xavigiro** [imatge-upc/memory-2016-fpv#1]
Hi @marccarne , could you please rename the folder with the source code of your web tool to "memorygame". Also, if you could provide some basic details about how to run it (I remember you showed me a instruction on python), this could help @agilmor to set up your web server.

Thanks !

**Comment by marccarne** [comment]
Hi @xavigiro and @agilmor,
I've renamed the folder.
In my computer, to create an "internal server" I go to the folder where the index.html is located and use the follow comand:
python -m http.server 8000

The 'html' file is creates to obtain the images from that folder. The 'html' file have some headers and text and a line that show an image. There is a javascript linked that have the whole algorithm and update each 1.4 seconds the source name of the image to shown.
